version: "3"

services:
  gitea:
    container_name: gitea
    image: patrickthedev/gitea-rpi:latest
    restart: unless-stopped
    volumes:
      - ./gitea_data:/data
    ports:
      - "3000:3000"
      - "2200:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    labels:
      ## Allow WatchTower to update this container.
      - com.centurylinklabs.watchtower.enable=true
