version: "3"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./homer/assets/:/www/assets
    ports:
      - 8002:8080
    environment:
      - UID=1000
      - GID=1000
    labels:
      ## Allow WatchTower to update this container.
      - com.centurylinklabs.watchtower.enable=true
