version: "3"

volumes:
  portainer_ce:

services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_ce:/data
    labels:
      ## Allow WatchTower to update this container.
      - com.centurylinklabs.watchtower.enable=true
