version: "3"

volumes:
  uptime-kuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptime-kuma:/app/data
    ports:
      - 3001:3001
    extra_hosts:
      - ${HOST}:192.168.1.4
      - ${HASSIOHOST}:192.168.1.4
    labels:
      ## Allow WatchTower to update this container.
      - com.centurylinklabs.watchtower.enable=true